project:
  type: book
  output-dir: docs
  
execute: 
  warning: FALSE
  message: FALSE
  cache: true
  freeze: auto

comments:
  hypothesis: 
    theme: clean

book:
  title: "Groundwater Availability in the upper Snake River Watershed"
  author: "Jeff Baldock"
  date: today
  chapters:
    - index.qmd
    - methods-results.qmd
    - springprevalence.qmd
    - groundwaterindex.qmd

format:
  html:
    theme: 
      light: cosmo
      dark: darkly
    code-fold: true
    code-tools: true
    code-overflow: wrap
    number-depth: 4
        
    include-in-header:
      - file: github-corner.html
    code-link: true
      
  pdf:
    documentclass: scrreprt

editor: source